---

- name: Install Logstash
  apt:
   name: logstash
   state: present

- name: Configure Beats configuration file
  template:
   src: beats-input.conf.j2
   dest: /etc/logstash/conf.d/02-beats-input.conf

- name: Configure Syslog Filter
  template:
   src: syslog-filter.conf.j2
   dest: /etc/logstash/conf.d/10-syslog-filter.conf

- name: Configure Elasticsearch output file
  template:
   src: elasticsearch-output.conf.j2
   dest: /etc/logstash/conf.d/30-elasticsearch-output.conf

- name: Start Logstash service
  systemd:
   name: logstash
   state: restarted
