---

- name: Fixing broken package on ubuntu
  shell: apt-get update --fix-missing

- name: Install/Upgrade Java 11
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Logstash apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

- name: Installing apt-transport-https package
  apt:
    name: apt-transport-https
    state: present

- name: Adding Logstash repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
   state: present
